name: olga
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ">=2.15.1 <3.0.0"

# versions available, run `flutter pub outdated`.
dependencies:
  flutter_localizations:
    sdk: flutter
  agora_rtc_engine: ^5.2.0
  agora_uikit: ^1.0.2
  awesome_snackbar_content: ^0.0.8
  cached_network_image: ^3.2.2
  circular_profile_avatar: ^2.0.5
  country_calling_code_picker: ^2.0.1
  country_code_picker: null
  country_list_pick: null
  country_picker: null
  crypto: ^3.0.2
  csc_picker: ^0.2.6
  cupertino_icons: ^1.0.5
  date_time_picker: ^2.1.0
  datetime_picker_formfield: ^2.0.0
  dio: ^4.0.6
  dotted_border: ^2.0.0+2
  dotted_line: ^3.1.0
  firebase_auth: ^4.1.5
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.3
  fl_chart: ^0.55.0
  fl_country_code_picker: ^0.0.3+1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.4.1
  flutter_lints: ^2.0.1
  flutter_local_notifications: ^9.9.1
  flutter_markdown: ^0.6.10+2
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_stripe: ^3.2.0
  flutter_svg: null
  flutter_switch: ^0.3.2
  flutter_typeahead: null
  fluttertoast: ^8.0.9
  get: ^4.6.5
  get_it: ^7.2.0
  google_sign_in: ^5.3.3
  graphic: ^0.10.5
  http: ^0.13.4
  image_picker: ^0.8.5+3
  in_app_review: ^2.0.4
  intl: ^0.17.0
  local_auth: ^2.1.2
  lottie: null
  package_info_plus: null
  pdf: ^3.8.3
  permission_handler: null
  pin_code_fields: ^7.4.0
  printing: ^5.9.3
  provider: ^6.0.3
  quiver: ^3.1.0
  shared_preferences: ^2.0.15
  shimmer: null
  shimmer_image: ^0.0.2
  sign_in_with_apple: ^4.1.0
  syncfusion_flutter_charts: ^20.2.36
  url_launcher: ^6.1.5
  video_player: ^2.4.5
  flutter_tts: ^3.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/flags/
    - assets/icons/
    - assets/icons/social/
    - assets/images/
    - assets/languages/
    - assets/mp3/
    - assets/videos/

  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
